---
abstract: 'Parser for Synopsys Liberty files'
author:
  - 'Gagarin Eugene <mosfet07@ya.ru>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.112621'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Parse-Liberty
no_index:
  directory:
    - t
    - inc
requires: {}
version: 0.1
